name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        id: docker-build
        with: 
          push: false
          tags: ${{ github.event.repository.name }}:build
      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
